---
version: '3'

services:
  api:
    image: devopsfaith/krakend:1.3
    ports:
      - "8000:8080"
      - "8010:8090"
    volumes:
      - ./configs/krakend.json:/etc/krakend/krakend.json
    command: run -d -c /etc/krakend/krakend.json

    # http://localhost:8010/__stats
    # http://localhost:8000/show/9999